stages:
  - build
  - run

task_1_build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - dotnet build lab_1/task_1/task_1.csproj
  artifacts:
    paths:
      - lab_1/task_2/bin/Debug/net6.0/*
  
task_1_run:
  stage: run
  image: mcr.microsoft.com/dotnet/runtime:6.0
  dependencies:
    - task_1_build
  script:
    - echo $MONEY
    - dotnet lab_1/task_1/bin/Debug/net6.0/task_1.dll $MONEY > answer.txt
  artifacts:
    paths:
      - answer.txt
  